CREATE TABLE IF NOT EXISTS users  (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS books  (
id BIGSERIAL PRIMARY KEY,
title VARCHAR(50) NOT NULL,
author VARCHAR(50) NOT NULL,
description VARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS loans  (
id BIGSERIAL PRIMARY KEY,
book_id BIGINT REFERENCES books(id) NOT NULL,
user_id BIGINT REFERENCES users(id) NOT NULL,
taken_at TIMESTAMP NOT NULL,
returned_at TIMESTAMP
);